### ISSUE TITLE
CryptoAnalysis dependency

### ISSUE THREAD

**Issue by martinschaef** [MagpieBridge/CryptoLSPDemo#11]
Looks like de.fraunhofer.iem:CryptoAnalysis:jar moved. Where can I get that from? I found it on GH, but its not published in the nexus anymore.

**Comment by linghuiluo** [comment]
@martinschaef  Hi, you can find the jar file here in ` CryptoAnalysis-2.1.1.zip `
under this link https://github.com/MagpieBridge/CryptoLSPDemo/releases/tag/CogniCryptLSP-0.0.1

**Comment by martinschaef** [comment]
Thx!
