### ISSUE TITLE
getting error while building the project

### ISSUE THREAD

**Issue by mgupta0421** [MagpieBridge/CryptoLSPDemo#18]
[cryptoLSPDemo_log.pdf](https://github.com/MagpieBridge/CryptoLSPDemo/files/6170850/cryptoLSPDemo_log.pdf)

Hi, 
I am facing to build the project. Please find the attached document to see the logs.
Thank You

**Comment by linghuiluo** [comment]
hi, you need to build the jars by yourself 
https://github.com/MagpieBridge/CryptoAnalysis 
https://github.com/MagpieBridge/WPDS

**Comment by linghuiluo** [comment]
You need to read carefully the "Build the Project" section in the readme file and do everything it tells you to do.
